<?php

include 'Empolyee_Jobs.php';

static $all_empolyees;
/*hook_init*/
function empolyee_init(){
//	$empolyee = new Empolyee_Testing("osama","mohsen");

//	drupal_set_message($empolyee->getName()+","+$empolyee->getPassword());
}
//function get_All_Empolyess(){
//	return $result = Database::getConnection()->query("SELECT * FROM {node}");
//}
/*hook_menu*/
function empolyee_menu(){

	$empolyee = new Empolyee_Jobs();

	$items = array();
//	http://localhost/drupal-7.52/?q=empolyeepage
	$items['empolyeepage'] = array(
		'title' => 'my empolyees Page',
		'description' => 'Description of empolyees Page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('empolyee_showempolyees'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);


	$items['customerpage'] = array(
		'title' => 'my customer Page',
		'description' => 'Description of customers Page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('empolyee_showcustomer'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);


	$items['customerpageUpdatge'] = array(
		'title' => 'Development Empolyee Updated',
		'description' => 'Description of empolyees Updated Page',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('empolyee_showcustomerUpdate'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	return $items;
}


function empolyee_showcustomer(){

	$form = array();
	$result = db_query("select title,field_phone_value,field_address_value from node as n
						INNER JOIN field_data_field_phone as j
						ON n.nid = j.entity_id
						INNER JOIN field_data_field_address as a
						ON j.entity_id = a.entity_id WHERE n.type = 'customer'");

	$header = array("Name","Address","Phone");
	foreach ($result as $res){
		$rows [] =array(
			$res->title,
			$res->field_address_value,
			$res->field_phone_value
		);
	}
	$output = theme('table',array('header'=>$header,'rows'=>$rows));
	$form['#suffix'] = "<div>$output</div>";
	return $form;
}

function empolyee_showcustomerUpdate(){

	$form = array();
	$entity = new EntityFieldQuery();
	$result = $entity->entityCondition('entity_type', 'node')
				->propertyCondition('type','customer')->execute();
	if(isset($result['node'])){
		$keys = array();
		foreach ($result['node'] as $res){
			$keys []= $res->nid;
		}

		echo "Done";
		$news_items_nids = array_keys($keys);
//		print ($news_items_nids);
		echo "<br />";
		$news_items = entity_load('node', $news_items_nids);

		$phones = $entity->entityCondition('entity_type','node')
			->propertyCondition('entity_id','field_data_field_phone')->execute();
//			->entityCondition('entity_id',$keys,'IN')->execute();
//			->propertyCondition('entity_id',$keys,'=')->execute();
		if(isset($phones)){
			foreach ($phones['field_data_field_phone'] as $res)
				echo $res->entity_id;
		}else {
			echo "not Done";
		}
//		$news_items->tostring();
//		echo count($result['node']);
//		dd($result);
//		foreach ($result as $res){
//			echo $res->
//		}
	}
	else echo "not Done";
//	$result = db_query("select * from node WHERE n.type = 'customer'");

//	foreach ($result as $res){
//
//	}
//	$result = entity_load('node',$result,'node.type=customer','false');
//
//	$header = array("Name","Address","Phone");
//	foreach ($result as $res){
//		$rows [] =array(
//			$res->title,
//			$res->field_address_value,
//			$res->field_phone_value
//		);
//	}
//	$output = theme('table',array('header'=>$header,'rows'=>$rows));
//	$form['#suffix'] = "<div>$output</div>";
	return $form;
}

function empolyee_showempolyees(){


	$form = array();
	$result = db_query("select title,field_job_value,field_age_value from node as n
						INNER JOIN field_data_field_job as j
						ON n.nid = j.entity_id
						INNER JOIN field_data_field_age as a
						ON j.entity_id = a.entity_id WHERE n.type = 'empolyee'");
	if($result->rowCount()>0){

		$header = array("Name","Job","Age");
		foreach ($result as $res){
			$rows [] =array(
				$res->title,
				$res->field_job_value,
				$res->field_age_value
			);
		}
		$output = theme('table',array('header'=>$header,'rows'=>$rows));
		$form['#suffix'] = "<div>$output</div>";
		return $form;
//		echo $output;
	}else{
		drupal_set_message("No Empolyees in your Company");
	}
}

function empolyee_showmydepart(){

//	return
}
//function empolyee_ajaxCallHandler(){
//	echo "arrived Heree";
//}

/*
Form Data of showempolyeeForm
*/

//function empolyee_showempolyeeForm(){
//
//	$form = array();
//
//	$form ['name'] = array(
//		'#type' => 'textfield',
//		'#title' => 'Please Enter your Form'
//	);
//
//	$form['submit'] = array(
//		'#type' => 'submit',
//		'#value' => 'submit'
//	);

//	$form['#submit'][] = 'empolyee_showempolyeeForm_submit';
//
//	/*Form with Ajax Button*/
//	$form['#suffix'] = '<input type="button" id="submitAjaxButton" value="Submit with Ajax" /> <br />
//	<div id="message-display-area"></div>';
//
//
//	drupal_add_js(drupal_get_path('module','empolyee')."/empolyee.js");
//	return $form;

//}

/*
submit function
*/

//function empolyee_showempolyeeForm_submit($form,&$form_state){


//	if ($form_state['values']['name']==""){
//		form_set_error('name','name is required');
//	}else{
//		drupal_set_message ('arrived here '.$form_state['values']['name']);
//	}
//}
?>
